"""Check-in service for UniThrive.

Handles business logic for daily check-ins and activity tracking.
"""

from datetime import date, datetime, timedelta
from typing import List, Optional

from app.schemas.checkin import CheckIn, CheckInCreate, ActivityRecord, ActivityRecordCreate
from app.storage.json_storage import JsonCheckInStorage, JsonActivityStorage


class CheckInService:
    """Service for managing check-ins and activities."""
    
    def __init__(self):
        self.checkin_storage = JsonCheckInStorage()
        self.activity_storage = JsonActivityStorage()
    
    async def create_checkin(self, checkin_data: CheckInCreate) -> CheckIn:
        """Create a new daily check-in.
        
        Args:
            checkin_data: The check-in data to create
            
        Returns:
            The created check-in
        """
        checkin = CheckIn(
            id="",  # Will be generated by storage
            user_id=checkin_data.user_id,
            timestamp=datetime.now(),
            mood_score=checkin_data.mood_score,
            stress_score=checkin_data.stress_score,
            sleep_hours=checkin_data.sleep_hours,
            exercise_minutes=checkin_data.exercise_minutes,
            social_interactions=checkin_data.social_interactions,
            notes_text=checkin_data.notes_text
        )
        return await self.checkin_storage.create(checkin)
    
    async def get_user_checkins(
        self, 
        user_id: str, 
        days: int = 30
    ) -> List[CheckIn]:
        """Get check-ins for a user.
        
        Args:
            user_id: The user ID
            days: Number of days to look back
            
        Returns:
            List of check-ins
        """
        end_date = date.today()
        start_date = end_date - timedelta(days=days)
        return await self.checkin_storage.get_by_user_id(
            user_id, 
            start_date=start_date, 
            end_date=end_date
        )
    
    async def get_today_checkins(self, user_id: str) -> List[CheckIn]:
        """Get today's check-ins for a user.
        
        Args:
            user_id: The user ID
            
        Returns:
            List of today's check-ins
        """
        return await self.checkin_storage.get_by_user_and_date(user_id, date.today())
    
    async def get_checkin_streak(self, user_id: str) -> int:
        """Calculate the current check-in streak for a user.
        
        Args:
            user_id: The user ID
            
        Returns:
            Number of consecutive days with check-ins
        """
        checkins = await self.get_user_checkins(user_id, days=365)
        if not checkins:
            return 0
        
        # Get unique dates with check-ins
        checkin_dates = set()
        for checkin in checkins:
            checkin_date = checkin.timestamp.date() if isinstance(checkin.timestamp, datetime) else checkin.timestamp
            checkin_dates.add(checkin_date)
        
        # Calculate streak
        streak = 0
        current_date = date.today()
        
        while current_date in checkin_dates:
            streak += 1
            current_date -= timedelta(days=1)
        
        return streak
    
    async def create_activity(self, activity_data: ActivityRecordCreate) -> ActivityRecord:
        """Create a new activity record.
        
        Args:
            activity_data: The activity data to create
            
        Returns:
            The created activity record
        """
        activity = ActivityRecord(
            id="",  # Will be generated by storage
            user_id=activity_data.user_id,
            date=activity_data.date,
            type=activity_data.type,
            duration_minutes=activity_data.duration_minutes,
            tag_ring=activity_data.tag_ring,
            title=activity_data.title,
            description=activity_data.description,
            created_at=datetime.now()
        )
        return await self.activity_storage.create(activity)
    
    async def get_user_activities(
        self,
        user_id: str,
        days: int = 30,
        activity_type: Optional[str] = None
    ) -> List[ActivityRecord]:
        """Get activities for a user.
        
        Args:
            user_id: The user ID
            days: Number of days to look back
            activity_type: Optional filter by activity type
            
        Returns:
            List of activities
        """
        end_date = date.today()
        start_date = end_date - timedelta(days=days)
        return await self.activity_storage.get_by_user_id(
            user_id,
            start_date=start_date,
            end_date=end_date,
            activity_type=activity_type
        )
    
    async def get_daily_summary(self, user_id: str, target_date: date) -> dict:
        """Get a summary of a user's day.
        
        Args:
            user_id: The user ID
            target_date: The date to summarize
            
        Returns:
            Dictionary with daily summary statistics
        """
        checkins = await self.checkin_storage.get_by_user_and_date(user_id, target_date)
        activities = await self.activity_storage.get_by_user_id(
            user_id,
            start_date=target_date,
            end_date=target_date
        )
        
        total_activity_minutes = sum(a.duration_minutes for a in activities)
        
        mood_avg = None
        stress_avg = None
        sleep_avg = None
        
        if checkins:
            mood_avg = sum(c.mood_score for c in checkins) / len(checkins)
            stress_avg = sum(c.stress_score for c in checkins) / len(checkins)
            sleep_avg = sum(c.sleep_hours for c in checkins) / len(checkins)
        
        return {
            "date": target_date.isoformat(),
            "user_id": user_id,
            "check_in_count": len(checkins),
            "activity_count": len(activities),
            "total_activity_minutes": total_activity_minutes,
            "mood_average": round(mood_avg, 2) if mood_avg else None,
            "stress_average": round(stress_avg, 2) if stress_avg else None,
            "sleep_average": round(sleep_avg, 2) if sleep_avg else None
        }


# Global service instance
checkin_service = CheckInService()
